---
## file: roles/ansible-pdns/tasks/main.yml

- debug:
    msg: "OS is {{ ansible_distribution }}_{{ ansible_distribution_major_version }}"

- name: Getting vars from the distro specific file
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
      - "_pdns_default.yml"

- name: Include distro specific tasks
  include: "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"

