---
## file: roles/ansible-pdns/tasks/main.yml

- name: Getting vars from the distro specific file
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
      - "_pdns_default.yml"

block:
  - name: (CentOS 7) Installing the EPEL, yum-plugin-priorities packages
    yum:
      name: "{{ item }}"
      state: latest
      update_cache: yes
    with_items:
      - epel-release
      - yum-plugin-priorities

  - name: (CentOS 7) Adding the PowerDNS 4.0.x YUM repo
    yum_repository:
      name: pdns
      state: present
      description: PowerDNS YUM repository
      baseurl: https://repo.powerdns.com/repo-files/centos-auth-40.repo
      gpgkey: https://repo.powerdns.com/CBC8B383-pub.asc
      gpgcheck: yes

when: "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}" == "CentOS_7"